application: starry-iris-830
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /css
  static_dir: bootstrap/css

- url: /fonts
  static_dir: bootstrap/fonts

- url: /js
  static_dir: bootstrap/js

- url: /images
  static_dir: images

- url: /.*
  script: schedule-equipment.application

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest
